[preset]
name = "ocaml"
description = "OCaml development environment"
order = 10

[packages]
required = ["bintools", "clang", "ocaml", "ocamlPackages.dream", "ocamlPackages.dune_3", "ocamlPackages.findlib", "ocamlPackages.ocaml-lsp", "ocamlPackages.ocamlformat"]
